require 'test/unit'
require_relative 'people_power'

class TestPeoplePower < Test::Unit::TestCase

  def test_all
    assert_equal("1", PeoplePower.show(1), "Testing 1")
    assert_equal("2", PeoplePower.show(2), "Testing 2")
    assert_equal("People", PeoplePower.show(3), "Testing 3")
    assert_equal("4", PeoplePower.show(4), "Testing 4")
    assert_equal("Power", PeoplePower.show(5), "Testing 5")
    assert_equal("People", PeoplePower.show(6), "Testing 6")
    assert_equal("7", PeoplePower.show(7), "Testing 7")
    assert_equal("8", PeoplePower.show(8), "Testing 8")
    assert_equal("People", PeoplePower.show(9), "Testing 9")
    assert_equal("Power", PeoplePower.show(10), "Testing 10")
    assert_equal("11", PeoplePower.show(11), "Testing 11")
    assert_equal("People", PeoplePower.show(12), "Testing 12")
    assert_equal("13", PeoplePower.show(13), "Testing 13")
    assert_equal("14", PeoplePower.show(14), "Testing 14")
    assert_equal("People Power", PeoplePower.show(15), "Testing 15")
    assert_equal("16", PeoplePower.show(16), "Testing 16")
    assert_equal("17", PeoplePower.show(17), "Testing 17")
    assert_equal("People", PeoplePower.show(18), "Testing 18")
    assert_equal("19", PeoplePower.show(19), "Testing 19")
    assert_equal("Power", PeoplePower.show(20), "Testing 20")
    assert_equal("People", PeoplePower.show(21), "Testing 21")
    assert_equal("22", PeoplePower.show(22), "Testing 22")
    assert_equal("23", PeoplePower.show(23), "Testing 23")
    assert_equal("People", PeoplePower.show(24), "Testing 24")
    assert_equal("Power", PeoplePower.show(25), "Testing 25")
    assert_equal("26", PeoplePower.show(26), "Testing 26")
    assert_equal("People", PeoplePower.show(27), "Testing 27")
    assert_equal("28", PeoplePower.show(28), "Testing 28")
    assert_equal("29", PeoplePower.show(29), "Testing 29")
    assert_equal("People Power", PeoplePower.show(30), "Testing 30")
    assert_equal("31", PeoplePower.show(31), "Testing 31")
    assert_equal("32", PeoplePower.show(32), "Testing 32")
    assert_equal("People", PeoplePower.show(33), "Testing 33")
    assert_equal("34", PeoplePower.show(34), "Testing 34")
    assert_equal("Power", PeoplePower.show(35), "Testing 35")
    assert_equal("People", PeoplePower.show(36), "Testing 36")
    assert_equal("37", PeoplePower.show(37), "Testing 37")
    assert_equal("38", PeoplePower.show(38), "Testing 38")
    assert_equal("People", PeoplePower.show(39), "Testing 39")
    assert_equal("Power", PeoplePower.show(40), "Testing 40")
    assert_equal("41", PeoplePower.show(41), "Testing 41")
    assert_equal("People", PeoplePower.show(42), "Testing 42")
    assert_equal("43", PeoplePower.show(43), "Testing 43")
    assert_equal("44", PeoplePower.show(44), "Testing 44")
    assert_equal("People Power", PeoplePower.show(45), "Testing 45")
    assert_equal("46", PeoplePower.show(46), "Testing 46")
    assert_equal("47", PeoplePower.show(47), "Testing 47")
    assert_equal("People", PeoplePower.show(48), "Testing 48")
    assert_equal("49", PeoplePower.show(49), "Testing 49")
    assert_equal("Power", PeoplePower.show(50), "Testing 50")
    assert_equal("People", PeoplePower.show(51), "Testing 51")
    assert_equal("52", PeoplePower.show(52), "Testing 52")
    assert_equal("53", PeoplePower.show(53), "Testing 53")
    assert_equal("People", PeoplePower.show(54), "Testing 54")
    assert_equal("Power", PeoplePower.show(55), "Testing 55")
    assert_equal("56", PeoplePower.show(56), "Testing 56")
    assert_equal("People", PeoplePower.show(57), "Testing 57")
    assert_equal("58", PeoplePower.show(58), "Testing 58")
    assert_equal("59", PeoplePower.show(59), "Testing 59")
    assert_equal("People Power", PeoplePower.show(60), "Testing 60")
    assert_equal("61", PeoplePower.show(61), "Testing 61")
    assert_equal("62", PeoplePower.show(62), "Testing 62")
    assert_equal("People", PeoplePower.show(63), "Testing 63")
    assert_equal("64", PeoplePower.show(64), "Testing 64")
    assert_equal("Power", PeoplePower.show(65), "Testing 65")
    assert_equal("People", PeoplePower.show(66), "Testing 66")
    assert_equal("67", PeoplePower.show(67), "Testing 67")
    assert_equal("68", PeoplePower.show(68), "Testing 68")
    assert_equal("People", PeoplePower.show(69), "Testing 69")
    assert_equal("Power", PeoplePower.show(70), "Testing 70")
    assert_equal("71", PeoplePower.show(71), "Testing 71")
    assert_equal("People", PeoplePower.show(72), "Testing 72")
    assert_equal("73", PeoplePower.show(73), "Testing 73")
    assert_equal("74", PeoplePower.show(74), "Testing 74")
    assert_equal("People Power", PeoplePower.show(75), "Testing 75")
    assert_equal("76", PeoplePower.show(76), "Testing 76")
    assert_equal("77", PeoplePower.show(77), "Testing 77")
    assert_equal("People", PeoplePower.show(78), "Testing 78")
    assert_equal("79", PeoplePower.show(79), "Testing 79")
    assert_equal("Power", PeoplePower.show(80), "Testing 80")
    assert_equal("People", PeoplePower.show(81), "Testing 81")
    assert_equal("82", PeoplePower.show(82), "Testing 82")
    assert_equal("83", PeoplePower.show(83), "Testing 83")
    assert_equal("People", PeoplePower.show(84), "Testing 84")
    assert_equal("Power", PeoplePower.show(85), "Testing 85")
    assert_equal("86", PeoplePower.show(86), "Testing 86")
    assert_equal("People", PeoplePower.show(87), "Testing 87")
    assert_equal("88", PeoplePower.show(88), "Testing 88")
    assert_equal("89", PeoplePower.show(89), "Testing 89")
    assert_equal("People Power", PeoplePower.show(90), "Testing 90")
    assert_equal("91", PeoplePower.show(91), "Testing 91")
    assert_equal("92", PeoplePower.show(92), "Testing 92")
    assert_equal("People", PeoplePower.show(93), "Testing 93")
    assert_equal("94", PeoplePower.show(94), "Testing 94")
    assert_equal("Power", PeoplePower.show(95), "Testing 95")
    assert_equal("People", PeoplePower.show(96), "Testing 96")
    assert_equal("97", PeoplePower.show(97), "Testing 97")
    assert_equal("98", PeoplePower.show(98), "Testing 98")
    assert_equal("People", PeoplePower.show(99), "Testing 99")
    assert_equal("Power", PeoplePower.show(100), "Testing 100")
  end

end